


CREATE TABLE USUARIO1 (ID_USUARIO INTEGER PRIMARY KEY AUTO_INCREMENT,
             NOMBRE VARCHAR(250), EDAD INTEGER, SUELDO FLOAT);



CREATE TABLE DIRECCION2 (ID_DIRECCION INTEGER PRIMARY KEY AUTO_INCREMENT,
ID_USUARIO INTEGER, CALLE VARCHAR(250),CP INTEGER, COLONIA VARCHAR(300), ESTADO VARCHAR(200),
    CONSTRAINT FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO));
